dist: focal
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install libgnutls28-dev
  - "pip install -U pip"
  - pip install codecov
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "pip install -r requirements.txt"
script:
  - flake8 arm
  - pytest arm/main.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov -t CODECOV_TOKEN

